# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
php-version = "8.4.0"

[source]
workspace = "."
paths = ["app/", "database/factories/", "database/seeders/", "tests/"]
includes = ["vendor"]
excludes = []

[formatter]
preset = "pint"
print-width = 80
tab-width = 4
use-tabs = true
function-brace-style = 'same_line'
method-brace-style = 'same_line'
preserve-breaking-member-access-chain = true

[linter]
integrations = ["laravel", "pest"]

[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
halstead = { effort-threshold = 7000 }
no-empty = { enabled = false }
no-else-clause = { enabled = false }
no-literal-password = { enabled = false } # password cast
too-many-properties = { threshold = 20 } # livewire forms

[analyzer]
plugins = []
find-unused-definitions = true
find-unused-expressions = true
analyze-dead-code = true
memoize-properties = true
allow-possibly-undefined-array-keys = false
check-throws = true
check-missing-override = true
find-unused-parameters = true
strict-list-index-checks = true
no-boolean-literal-comparison = true
check-missing-type-hints = true
register-super-globals = true
